"""Environment-backed settings for workspace_execution.

The values are generated by the root config center. This module only reads the
runtime surface exposed to the service container.
"""

import json
import os
from dataclasses import dataclass
from functools import cache
from pathlib import Path


def _read_secret_file(path: str) -> str:
    try:
        return Path(path).read_text(encoding="utf-8").strip()
    except OSError:
        return ""


def _int_env(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return default
    return int(raw)


@dataclass(frozen=True)
class SecuritySettings:
    api_key: str


@dataclass(frozen=True)
class StorageGuardianSettings:
    url: str
    token: str
    verify_tls: bool
    timeout_seconds: float
    max_inline_bytes: int
    agent: str
    store: str
    zone: str


@dataclass(frozen=True)
class WorkspaceExecutionSettings:
    scratch_root: Path
    source_roots: dict[str, Path]
    host_read_host_root: Path | None
    host_read_container_root: Path | None
    session_ttl_seconds: int
    command_timeout_seconds: int
    max_output_bytes: int
    runner_backend: str
    runner_image: str
    runner_cpu_limit: float
    runner_memory_limit: str
    runner_pids_limit: int
    sandbox_runtime: str
    require_runtime: bool
    vm_backend: str
    vm_control_url: str
    vm_control_token: str
    vm_image_ref: str
    vm_profile: str
    vm_qemu_binary: str
    vm_kernel_path: str
    vm_kvm_device: str
    vm_require_kvm: bool
    vm_cache_root: Path
    vm_boot_timeout_seconds: int
    vm_prewarm_rootfs: bool
    vm_ttl_seconds: int
    vm_cpu_limit: float
    vm_memory_limit: str
    vm_disk_limit: str
    compose_runtime_url: str
    compose_runtime_token: str
    compose_runtime_timeout_seconds: int
    compose_runtime_backend: str
    compose_runtime_dind_image: str
    compose_runtime_runner_image: str
    security: SecuritySettings
    storage_guardian: StorageGuardianSettings


def _source_roots() -> dict[str, Path]:
    raw = os.environ.get("WORKSPACE_EXECUTION_SOURCE_ROOTS", "").strip()
    if raw:
        payload = _source_roots_payload(raw)
        if not isinstance(payload, dict):
            raise ValueError("WORKSPACE_EXECUTION_SOURCE_ROOTS must be a JSON object")
        return {str(key): Path(str(value)) for key, value in payload.items()}
    root = os.environ.get("AI_LOCAL_HOST_PROJECT_ROOT", "").strip()
    if root:
        return {"ai-local": Path(root)}
    return {"ai-local": Path.cwd()}


def _optional_path_env(name: str) -> Path | None:
    raw = os.environ.get(name, "").strip()
    return Path(raw) if raw else None


def _source_roots_payload(raw: str) -> dict[str, str]:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        payload = _compact_source_roots_payload(raw)
    if not isinstance(payload, dict):
        raise ValueError("WORKSPACE_EXECUTION_SOURCE_ROOTS must be a JSON object")
    return {str(key): str(value) for key, value in payload.items()}


def _compact_source_roots_payload(raw: str) -> dict[str, str]:
    text = raw.strip()
    if not (text.startswith("{") and text.endswith("}")):
        raise ValueError("WORKSPACE_EXECUTION_SOURCE_ROOTS must be a JSON object")
    body = text[1:-1].strip()
    if not body:
        return {}
    payload: dict[str, str] = {}
    for item in body.split(","):
        if ":" not in item:
            raise ValueError("WORKSPACE_EXECUTION_SOURCE_ROOTS compact entries must use name:path")
        key, value = item.split(":", 1)
        key = key.strip().strip("'\"")
        value = value.strip().strip("'\"")
        if not key or not value:
            raise ValueError("WORKSPACE_EXECUTION_SOURCE_ROOTS compact entries must include name and path")
        payload[key] = value
    return payload


def _float_env(name: str, default: float) -> float:
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return default
    return float(raw)


def _bool_env(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off"}


def _storage_guardian_settings() -> StorageGuardianSettings:
    token = os.environ.get("STORAGE_GUARDIAN_INTERNAL_TOKEN", "").strip()
    if not token:
        token_file = (
            os.environ.get("STORAGE_GUARDIAN_INTERNAL_TOKEN_FILE")
            or os.environ.get("INTERNAL_API_KEY_FILE")
            or os.environ.get("API_KEY_FILE")
            or ""
        ).strip()
        token = _read_secret_file(token_file) if token_file else ""
    return StorageGuardianSettings(
        url=(
            os.environ.get("STORAGE_GUARDIAN_URL")
            or os.environ.get("ORC_SERVICES_STORAGE_GUARDIAN_URL")
            or "https://storage-guardian:8730"
        ).rstrip("/"),
        token=token,
        verify_tls=_bool_env("STORAGE_GUARDIAN_VERIFY_TLS", True),
        timeout_seconds=_float_env("STORAGE_GUARDIAN_TIMEOUT_SECONDS", 60.0),
        max_inline_bytes=_int_env("STORAGE_GUARDIAN_MAX_INLINE_BYTES", 262_144),
        agent=os.environ.get("WORKSPACE_EXECUTION_STORAGE_GUARDIAN_AGENT", "symbiont"),
        store=os.environ.get("WORKSPACE_EXECUTION_STORAGE_GUARDIAN_STORE", "agent_outputs"),
        zone=os.environ.get("WORKSPACE_EXECUTION_STORAGE_GUARDIAN_ZONE", "ingest"),
    )


def _sandbox_runtime() -> str:
    value = os.environ.get("WORKSPACE_EXECUTION_SANDBOX_RUNTIME", "docker").strip().lower()
    if value not in {"docker", "runsc"}:
        raise ValueError("WORKSPACE_EXECUTION_SANDBOX_RUNTIME must be 'docker' or 'runsc'")
    return value


def _vm_backend() -> str:
    value = os.environ.get("WORKSPACE_EXECUTION_VM_BACKEND", "unavailable").strip().lower()
    if value not in {"unavailable", "external", "microvm", "vm-proxy"}:
        raise ValueError("WORKSPACE_EXECUTION_VM_BACKEND must be unavailable, external, microvm, or vm-proxy")
    return value


def _vm_control_token() -> str:
    token = os.environ.get("WORKSPACE_EXECUTION_VM_CONTROL_TOKEN", "").strip()
    if token:
        return token
    token_file = os.environ.get("WORKSPACE_EXECUTION_VM_CONTROL_TOKEN_FILE", "").strip()
    return _read_secret_file(token_file) if token_file else ""


def _compose_runtime_token() -> str:
    token = os.environ.get("WORKSPACE_EXECUTION_COMPOSE_RUNTIME_TOKEN", "").strip()
    if token:
        return token
    token_file = os.environ.get("WORKSPACE_EXECUTION_COMPOSE_RUNTIME_TOKEN_FILE", "").strip()
    return _read_secret_file(token_file) if token_file else ""


@cache
def get_settings() -> WorkspaceExecutionSettings:
    api_key = os.environ.get("API_KEY", "").strip()
    if not api_key:
        secret_file = os.environ.get("API_KEY_FILE", "").strip()
        api_key = _read_secret_file(secret_file) if secret_file else ""
    return WorkspaceExecutionSettings(
        scratch_root=Path(os.environ.get("WORKSPACE_EXECUTION_SCRATCH_ROOT", "/tmp/workspace_execution")),
        source_roots=_source_roots(),
        host_read_host_root=_optional_path_env("WORKSPACE_EXECUTION_HOST_READ_HOST_ROOT"),
        host_read_container_root=_optional_path_env("WORKSPACE_EXECUTION_HOST_READ_CONTAINER_ROOT"),
        session_ttl_seconds=_int_env("WORKSPACE_EXECUTION_SESSION_TTL_SECONDS", 3600),
        command_timeout_seconds=_int_env("WORKSPACE_EXECUTION_COMMAND_TIMEOUT_SECONDS", 120),
        max_output_bytes=_int_env("WORKSPACE_EXECUTION_MAX_OUTPUT_BYTES", 20000),
        runner_backend=os.environ.get("WORKSPACE_EXECUTION_RUNNER_BACKEND", "docker_ephemeral"),
        runner_image=os.environ.get("WORKSPACE_EXECUTION_RUNNER_IMAGE", "ai-local-command-sandbox:latest"),
        runner_cpu_limit=_float_env("WORKSPACE_EXECUTION_RUNNER_CPU_LIMIT", 1.0),
        runner_memory_limit=os.environ.get("WORKSPACE_EXECUTION_RUNNER_MEMORY_LIMIT", "512m"),
        runner_pids_limit=_int_env("WORKSPACE_EXECUTION_RUNNER_PIDS_LIMIT", 256),
        sandbox_runtime=_sandbox_runtime(),
        require_runtime=_bool_env("WORKSPACE_EXECUTION_REQUIRE_RUNTIME", False),
        vm_backend=_vm_backend(),
        vm_control_url=os.environ.get("WORKSPACE_EXECUTION_VM_CONTROL_URL", "").strip().rstrip("/"),
        vm_control_token=_vm_control_token(),
        vm_image_ref=os.environ.get("WORKSPACE_EXECUTION_VM_IMAGE_REF", "ai-local-workspace-vm:latest"),
        vm_profile=os.environ.get("WORKSPACE_EXECUTION_VM_PROFILE", "material-default"),
        vm_qemu_binary=os.environ.get("WORKSPACE_EXECUTION_VM_QEMU_BINARY", "qemu-system-x86_64"),
        vm_kernel_path=os.environ.get("WORKSPACE_EXECUTION_VM_KERNEL_PATH", "").strip(),
        vm_kvm_device=os.environ.get("WORKSPACE_EXECUTION_VM_KVM_DEVICE_CONTAINER", "/dev/kvm"),
        vm_require_kvm=_bool_env("WORKSPACE_EXECUTION_VM_REQUIRE_KVM", True),
        vm_cache_root=Path(os.environ.get("WORKSPACE_EXECUTION_VM_CACHE_ROOT", "/tmp/workspace_execution_microvm")),
        vm_boot_timeout_seconds=_int_env("WORKSPACE_EXECUTION_VM_BOOT_TIMEOUT_SECONDS", 45),
        vm_prewarm_rootfs=_bool_env("WORKSPACE_EXECUTION_VM_PREWARM_ROOTFS", False),
        vm_ttl_seconds=_int_env("WORKSPACE_EXECUTION_VM_TTL_SECONDS", 3600),
        vm_cpu_limit=_float_env("WORKSPACE_EXECUTION_VM_CPU_LIMIT", 2.0),
        vm_memory_limit=os.environ.get("WORKSPACE_EXECUTION_VM_MEMORY_LIMIT", "4g"),
        vm_disk_limit=os.environ.get("WORKSPACE_EXECUTION_VM_DISK_LIMIT", "20g"),
        compose_runtime_url=os.environ.get("WORKSPACE_EXECUTION_COMPOSE_RUNTIME_URL", "").strip().rstrip("/"),
        compose_runtime_token=_compose_runtime_token(),
        compose_runtime_timeout_seconds=_int_env("WORKSPACE_EXECUTION_COMPOSE_RUNTIME_TIMEOUT_SECONDS", 30),
        compose_runtime_backend=os.environ.get(
            "WORKSPACE_EXECUTION_COMPOSE_RUNTIME_BACKEND",
            "dedicated-dind",
        ).strip(),
        compose_runtime_dind_image=os.environ.get(
            "WORKSPACE_EXECUTION_COMPOSE_RUNTIME_DIND_IMAGE",
            "docker:27-dind",
        ).strip(),
        compose_runtime_runner_image=os.environ.get(
            "WORKSPACE_EXECUTION_COMPOSE_RUNTIME_RUNNER_IMAGE",
            os.environ.get("WORKSPACE_EXECUTION_RUNNER_IMAGE", "ai-local-command-sandbox:latest"),
        ).strip(),
        security=SecuritySettings(api_key=api_key),
        storage_guardian=_storage_guardian_settings(),
    )
