"""Terminal launcher installer for the public Symbiont CLI commands.

Usage:
    make aliases            # installs @ and symbiont

After installation, only the public terminal commands are installed in PATH:

    @ olá!                                # → curl POST /query → streaming
    @ corrige este bug                    # → curl POST /query → streaming
    cat file.py | @ analisa este ficheiro # → stdin included in query
    symbiont                              # → Rust terminal chat UX
    symbiont -l                           # → Rust sessions/tasks UX

Scripts call the symbiont API via curl (requires symbiont running via ``make infra``).
Works on any OS, any shell — no .zshrc, .bashrc, or venv needed.
"""

from __future__ import annotations

import os
import stat
import tomllib
from pathlib import Path

import click

_ALIAS_MARKER = "# auto-generated by: ai-local install-aliases"
_ZSH_NOGLOB_BEGIN = "# >>> ai-local terminal alias @ >>>"
_ZSH_NOGLOB_END = "# <<< ai-local terminal alias @ <<<"


def _is_generated_alias_script(content: str) -> bool:
    return _ALIAS_MARKER in content


def _workspace_root() -> Path:
    """Return the ai-local workspace root for generated shell aliases."""
    project_root = Path(__file__).resolve().parent.parent.parent
    return project_root


def _secret_file_path() -> str:
    """Return the path to the Docker secret file containing ORC_SYMBIONT_API_KEY."""
    return str(_workspace_root() / "infra" / "docker" / "secrets" / "orc_api_key")


def _services_env_file_path() -> str:
    """Return the generated services env file used by the central config resolver."""
    return str(_workspace_root() / ".env.services.generated")


_SECRET_FILE = _secret_file_path()
_ENV_FILE_PATH = _services_env_file_path()
_DEFAULT_CLI_SESSION_STATE_FILE = str(_workspace_root() / ".local" / "data" / "symbiont" / "symbiont" / "cli_default_session")

# System commands that must never be shadowed by an alias script
_RESERVED_NAMES: frozenset[str] = frozenset({
    "code",    # VS Code
    "python", "python3", "pip", "pip3",
    "node", "npm", "npx",
    "git", "curl", "wget", "ssh", "bash", "zsh", "sh",
    "sudo", "su", "chmod", "chown", "rm", "mv", "cp", "ls",
})


def _user_bin_dir() -> Path:
    """Return the user-level bin directory (~/.local/bin on Linux/macOS).

    Creates the directory if it doesn't exist.
    """
    bin_dir = Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    return bin_dir


def _user_lib_dir() -> Path:
    """Return the private user-level directory for internal Symbiont helpers."""
    lib_dir = Path.home() / ".local" / "lib" / "ai-local"
    lib_dir.mkdir(parents=True, exist_ok=True)
    return lib_dir


def _render_script_path() -> str:
    """Return the path to the installed private Markdown renderer helper."""
    return str(_user_lib_dir() / "orc-render")


def _symbiont_tui_binary_path() -> str:
    """Return the path to the installed private Rust interactive terminal."""
    return str(_user_lib_dir() / "symbiont-tui")


def _symbiont_tui_crate_dir() -> Path:
    """Return the Rust terminal client crate directory."""
    return _workspace_root() / "crates" / "symbiont-tui"


def _install_zsh_noglob_alias(alias: str) -> bool:
    """Install a zsh alias so prompts after @ are not treated as globs."""
    if alias != "@":
        return False

    zshrc = Path.home() / ".zshrc"
    shell_name = Path(os.environ.get("SHELL", "")).name
    if not zshrc.exists() and shell_name != "zsh":
        return False

    block = "\n".join(
        [
            _ZSH_NOGLOB_BEGIN,
            "# Prevent zsh from treating ? * [] in @ prompts as filename globs.",
            "alias @='noglob @'",
            _ZSH_NOGLOB_END,
            "",
        ]
    )

    try:
        existing = zshrc.read_text(encoding="utf-8") if zshrc.exists() else ""
    except OSError:
        return False

    if _ZSH_NOGLOB_BEGIN in existing and _ZSH_NOGLOB_END in existing:
        before, rest = existing.split(_ZSH_NOGLOB_BEGIN, 1)
        _, after = rest.split(_ZSH_NOGLOB_END, 1)
        updated = before.rstrip() + "\n\n" + block + after.lstrip("\n")
    else:
        updated = existing.rstrip() + "\n\n" + block if existing.strip() else block

    if updated == existing:
        return True

    try:
        zshrc.write_text(updated, encoding="utf-8")
    except OSError:
        return False
    return True


def _parse_bool(value, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _config_dir_candidates() -> list[Path]:
    """Return likely workspace config directories for lightweight CLI settings."""
    here = Path(__file__).resolve()
    candidates: list[Path] = []
    env_dir = os.environ.get("AI_ORC_SETTINGS_DIR")
    if env_dir:
        candidates.append(Path(env_dir).expanduser())
    candidates.extend([
        here.parent.parent.parent.parent / "config" / "orc",
        Path.home() / "_projects" / "ai-local" / "config" / "orc",
        Path.home() / "ai-local" / "config" / "orc",
    ])
    return candidates


def _load_cli_session_settings() -> tuple[bool, str]:
    """Load only the CLI session settings without constructing full Settings."""
    env_enabled = os.environ.get("ORC_SESSION_CLI_DEFAULT_SESSION")
    env_state = os.environ.get("ORC_SESSION_CLI_SESSION_STATE_FILE")

    enabled: bool | None = None
    state_file = ""

    for config_dir in _config_dir_candidates():
        server_toml = config_dir / "server.toml"
        if not server_toml.exists():
            continue
        try:
            with server_toml.open("rb") as fh:
                session = tomllib.load(fh).get("session", {})
        except (OSError, tomllib.TOMLDecodeError):
            continue
        enabled = _parse_bool(session.get("cli_default_session"), default=False)
        state_file = str(session.get("cli_session_state_file") or "")
        break

    if env_enabled is not None:
        enabled = _parse_bool(env_enabled, default=False)
    if env_state:
        state_file = env_state

    if enabled and not state_file:
        state_file = _DEFAULT_CLI_SESSION_STATE_FILE

    return bool(enabled), state_file


def _client_system_probe_shell() -> str:
    """Return a small host-side read-only system probe for generated aliases."""
    return r'''
CLIENT_SYSTEM_JSON=$(python3 -c '
import glob, json, os, platform, shutil, subprocess, time

def run(cmd, timeout=2.5):
    try:
        return subprocess.check_output(cmd, text=True, stderr=subprocess.DEVNULL, timeout=timeout).strip()
    except Exception:
        return ""

snapshot = {
    "source": "terminal_alias",
    "observed_at": time.time(),
    "platform": platform.platform(),
}

try:
    proc_entries = [name for name in os.listdir("/proc") if name.isdigit()]
    snapshot["process_count"] = len(proc_entries)
except Exception:
    ps_output = run(["ps", "-e", "-o", "pid="])
    if ps_output:
        snapshot["process_count"] = len([line for line in ps_output.splitlines() if line.strip()])

try:
    meminfo = {}
    with open("/proc/meminfo", "r", encoding="utf-8") as fh:
        for line in fh:
            if ":" not in line:
                continue
            key, raw = line.split(":", 1)
            if key in {"MemTotal", "MemAvailable"}:
                meminfo[key] = int(raw.strip().split()[0])
    if "MemTotal" in meminfo:
        total_mb = round(meminfo["MemTotal"] / 1024)
        available_mb = round(meminfo.get("MemAvailable", 0) / 1024)
        snapshot["ram_total_mb"] = total_mb
        snapshot["ram_available_mb"] = available_mb
        snapshot["ram_used_mb"] = max(0, total_mb - available_mb)
        if total_mb:
            snapshot["ram_percent_used"] = round((1 - (available_mb / total_mb)) * 100, 1)
except Exception:
    free_output = run(["free", "-m"])
    for line in free_output.splitlines():
        parts = line.split()
        if parts and parts[0].lower().startswith("mem") and len(parts) >= 7:
            total_mb = int(parts[1])
            available_mb = int(parts[6])
            snapshot["ram_total_mb"] = total_mb
            snapshot["ram_available_mb"] = available_mb
            snapshot["ram_used_mb"] = max(0, total_mb - available_mb)
            if total_mb:
                snapshot["ram_percent_used"] = round((1 - (available_mb / total_mb)) * 100, 1)
            break

try:
    snapshot["cpu_count"] = os.cpu_count()
    def read_cpu():
        with open("/proc/stat", "r", encoding="utf-8") as fh:
            parts = fh.readline().split()[1:]
        values = [int(part) for part in parts[:8]]
        idle = values[3] + (values[4] if len(values) > 4 else 0)
        total = sum(values)
        return idle, total
    idle1, total1 = read_cpu()
    time.sleep(0.08)
    idle2, total2 = read_cpu()
    total_delta = max(1, total2 - total1)
    idle_delta = max(0, idle2 - idle1)
    snapshot["cpu_percent"] = round((1 - idle_delta / total_delta) * 100, 1)
except Exception:
    try:
        load1, _, _ = os.getloadavg()
        cpu_count = os.cpu_count() or 1
        snapshot["cpu_count"] = cpu_count
        snapshot["cpu_percent"] = round(min(100.0, (load1 / cpu_count) * 100), 1)
    except Exception:
        pass

def add_disk(prefix, path):
    try:
        usage = shutil.disk_usage(path)
        total_gb = usage.total / (1024 ** 3)
        free_gb = usage.free / (1024 ** 3)
        used_gb = usage.used / (1024 ** 3)
        snapshot[f"{prefix}_path"] = path
        snapshot[f"{prefix}_total_gb"] = round(total_gb, 1)
        snapshot[f"{prefix}_free_gb"] = round(free_gb, 1)
        snapshot[f"{prefix}_used_gb"] = round(used_gb, 1)
        snapshot[f"{prefix}_percent_used"] = round((used_gb / total_gb) * 100, 1) if total_gb else 0.0
    except Exception:
        pass

add_disk("disk", os.getcwd())
for storage_path in (
    os.environ.get("AI_STORAGE_EXTERNAL_ROOT"),
    os.environ.get("AI_LOCAL_STORAGE_ROOT"),
):
    if storage_path and os.path.exists(storage_path):
        add_disk("storage_disk", storage_path)
        break

def resolve_command(candidate):
    resolved = shutil.which(candidate)
    if resolved:
        return resolved
    if os.path.exists(candidate):
        return candidate
    return ""

def parse_gpu_csv(gpu_output, source):
    first = gpu_output.splitlines()[0] if gpu_output else ""
    if not first:
        return False
    parts = [part.strip() for part in first.split(",")]
    if len(parts) < 5:
        return False
    try:
        snapshot["gpu_name"] = parts[0]
        snapshot["gpu_vram_used_mb"] = int(float(parts[1]))
        snapshot["gpu_vram_free_mb"] = int(float(parts[2]))
        snapshot["gpu_vram_total_mb"] = int(float(parts[3]))
        snapshot["gpu_utilization_pct"] = float(parts[4])
        snapshot["gpu_detected_by"] = source
        return True
    except Exception:
        return False

def detect_gpu_from_procfs():
    for info_path in glob.glob("/proc/driver/nvidia/gpus/*/information"):
        try:
            fields = {}
            with open(info_path, "r", encoding="utf-8") as fh:
                for line in fh:
                    if ":" not in line:
                        continue
                    key, value = line.split(":", 1)
                    fields[key.strip().lower()] = value.strip()
            model = fields.get("model")
            if model:
                snapshot["gpu_name"] = model
                snapshot["gpu_detected_by"] = "procfs"
                if fields.get("bus location"):
                    snapshot["gpu_bus_id"] = fields["bus location"]
                return True
        except Exception:
            pass
    for dev_path in ("/dev/nvidia0", "/dev/dxg"):
        if os.path.exists(dev_path):
            snapshot["gpu_name"] = "NVIDIA GPU" if "nvidia" in dev_path else "GPU device"
            snapshot["gpu_detected_by"] = dev_path
            return True
    return False

gpu_query = [
    "--query-gpu=name,memory.used,memory.free,memory.total,utilization.gpu",
    "--format=csv,noheader,nounits",
]
disable_nvidia_smi_probe = os.environ.get("AI_LOCAL_DISABLE_NVIDIA_SMI_PROBE", "").strip().lower() in {"1", "true", "yes", "on"}
if not disable_nvidia_smi_probe:
    for candidate in (
        "nvidia-smi",
        "/usr/lib/wsl/lib/nvidia-smi",
        "nvidia-smi.exe",
        "/mnt/c/Windows/System32/nvidia-smi.exe",
    ):
        command = resolve_command(candidate)
        if not command:
            continue
        if parse_gpu_csv(run([command, *gpu_query], timeout=3.0), os.path.basename(command)):
            break
    else:
        detect_gpu_from_procfs()
else:
    detect_gpu_from_procfs()

print(json.dumps(snapshot, separators=(",", ":")))
' 2>/dev/null || printf '{}')
'''


def _client_file_probe_shell() -> str:
    """Return a host-side read-only file probe for paths mentioned in prompts."""
    return r'''
CLIENT_FILES_JSON=$(ORC_QUERY_FOR_FILE_PROBE="$QUERY" python3 -c '
import csv, json, mimetypes, os, re, shlex
from pathlib import Path

query = os.environ.get("ORC_QUERY_FOR_FILE_PROBE", "")
q = " ".join(query.lower().split())
candidates = []
text_exts = {
    ".csv", ".txt", ".md", ".json", ".yaml", ".yml", ".sql", ".py", ".r", ".ipynb", ".toml", ".ini", ".log"
}
file_exts = text_exts | {".sqlite", ".db"}
blocked_names = {"GROUND_TRUTH.md", "EVALUATION.md"}
blocked_terms = ("secret", "token", "password", "passwd", "credential", "apikey", "api_key")

def ext_for(path: Path) -> str:
    return path.suffix.lower()

def query_mentions_existing_local_path() -> bool:
    path_tokens = []
    try:
        path_tokens.extend(
            token.strip().strip(",.;:)】]}>" + chr(39) + chr(34) + chr(96))
            for token in shlex.split(query)
            if token.startswith(("/", "~/", "./", "../"))
        )
    except Exception:
        pass
    path_tokens.extend(match.group(0) for match in re.finditer(r"/[^\s\"`<>]+", query))
    for raw in path_tokens:
        cleaned = str(raw or "").strip().strip(".,;:)】]}>" + chr(39) + chr(34) + chr(96))
        if not cleaned:
            continue
        path = Path(cleaned).expanduser()
        if not path.is_absolute():
            path = (Path.cwd() / path).resolve()
        try:
            if path.exists():
                return True
        except OSError:
            continue
    return False

def looks_like_generation_request() -> bool:
    if query_mentions_existing_local_path():
        return False
    generation_terms = (
        "cria", "criar", "gera", "gerar", "constrói", "constroi", "construir",
        "build", "create", "generate", "scaffold", "implement",
    )
    deliverable_terms = (
        "artefacto", "artefato", "artifact", "projeto", "project", "pacote",
        "package", "cli", "readme", "pyproject", "teste", "test", "pytest",
        "materializa", "materializado", "materialized",
    )
    read_patterns = (
        r"\b(?:lê|le|ler|abre|abrir)\b",
        r"\b(?:analisa|analisar|inspeciona|inspecionar|resume|summarize)\b",
        r"\b(?:read|open|inspect|analyze|analyse)\b",
        r"\b(?:existing file|ficheiro existente|arquivo existente)\b",
        r"\b(?:neste ficheiro|neste arquivo|this file)\b",
    )
    return (
        any(term in q for term in generation_terms)
        and any(term in q for term in deliverable_terms)
        and not any(re.search(pattern, q) for pattern in read_patterns)
    )

if looks_like_generation_request():
    print("[]")
    raise SystemExit

def add_candidate(raw):
    cleaned = str(raw or "").strip().strip(",.;:")
    if cleaned:
        candidates.append(cleaned)

try:
    for token in shlex.split(query):
        cleaned = token.strip().strip(",.;:")
        if cleaned.startswith("/"):
            add_candidate(cleaned)
        elif ext_for(Path(cleaned)) in file_exts:
            add_candidate(cleaned)
except Exception:
    pass

for match in re.finditer(r"/[^\s\"`<>]+", query):
    add_candidate(match.group(0))

for match in re.finditer(r"(?<![\w/.-])[\w./-]+\.(?:csv(?:\.gz)?|tsv(?:\.gz)?|txt|md|json|jsonl(?:\.gz)?|ndjson(?:\.gz)?|ya?ml|sql|py|r|ipynb|toml|ini|log|sqlite|db)(?![\w.-])", query, flags=re.IGNORECASE):
    add_candidate(match.group(0))

seen = set()
files = []
for raw in candidates:
    if raw in seen or len(files) >= 5:
        continue
    seen.add(raw)
    path = Path(raw).expanduser()
    if not path.is_absolute():
        path = (Path.cwd() / path).resolve()
    name = path.name
    lowered = str(path).lower()
    if name in blocked_names or any(term in lowered for term in blocked_terms):
        continue
    info = {"path": str(path), "exists": path.exists()}
    try:
        if path.exists():
            stat = path.stat()
            info.update({
                "is_file": path.is_file(),
                "is_dir": path.is_dir(),
                "size_bytes": stat.st_size,
                "suffix": path.suffix.lower(),
                "mime_type": mimetypes.guess_type(str(path))[0],
            })
            if path.is_file() and path.suffix.lower() in text_exts:
                with path.open("rb") as fh:
                    text = fh.read(8192).decode("utf-8", errors="replace")
                info["preview"] = text[:8192]
                if stat.st_size <= 10_000_000:
                    full_text = path.read_text(encoding="utf-8", errors="replace")
                    info["line_count"] = len(full_text.splitlines())
                if path.suffix.lower() == ".csv":
                    rows = list(csv.reader(text.splitlines()[:3]))
                    if rows:
                        info["csv_columns"] = rows[0]
                    if len(rows) > 1:
                        info["csv_sample_row"] = rows[1]
    except Exception as exc:
        info["error"] = str(exc)[:200]
    files.append(info)

print(json.dumps(files, separators=(",", ":")))
' 2>/dev/null || printf '[]')
'''


def _build_script(
    alias: str,
    secret_file: str,
    *,
    cli_default_session: bool = False,
    session_state_file: str = "",
    services_env_file: str = "",
) -> str:
    """Build a bash/curl script that queries the symbiont API.

    Session continuity (persistent default session + --new-session reset) is
    enabled via ``cli_default_session`` and the ``session_state_file`` path —
    both sourced from the [session] config, never hardcoded.
    """
    render_path = _render_script_path()
    services_env_file = services_env_file or _ENV_FILE_PATH
    session_default_flag = "1" if cli_default_session else ""
    client_system_probe = _client_system_probe_shell()
    client_file_probe = _client_file_probe_shell()
    return f'''#!/usr/bin/env bash
{_ALIAS_MARKER}
# Model alias '{alias}' — calls symbiont API with model={alias}
set -euo pipefail

# --- Configuration ---
SERVICES_ENV_FILE="{services_env_file}"
ORC_API_URL="${{ORC_API_URL:-}}"
if [ -z "$ORC_API_URL" ] && [ -f "$SERVICES_ENV_FILE" ]; then
    ORC_PORT=$(sed -n 's/^ORC_PORT_SYMBIONT=//p' "$SERVICES_ENV_FILE" | tail -n 1 | tr -d '\\n\\r')
    if [ -n "$ORC_PORT" ]; then
        ORC_API_URL="https://127.0.0.1:$ORC_PORT"
    fi
fi
ORC_API_URL="${{ORC_API_URL:-https://127.0.0.1:8586}}"
SECRET_FILE="{secret_file}"
ORC_RENDER="{render_path}"

# Session continuity (config-driven): reuse a persistent default session so
# follow-up questions inherit conversation context. Reset with --new-session.
CLI_DEFAULT_SESSION="{session_default_flag}"
SESSION_STATE_FILE="{session_state_file}"

# --- Load API key from Docker secrets ---
if [ -z "${{ORC_SYMBIONT_API_KEY:-}}" ]; then
    if [ -f "$SECRET_FILE" ]; then
        ORC_SYMBIONT_API_KEY=$(cat "$SECRET_FILE" | tr -d '\\n\\r')
    fi
fi

if [ -z "${{ORC_SYMBIONT_API_KEY:-}}" ]; then
    echo "Error: API key not found." >&2
    echo "Set ORC_SYMBIONT_API_KEY env var or ensure $SECRET_FILE exists." >&2
    exit 1
fi

# --- Parse arguments ---
SESSION_ID=""
NEW_SESSION=""
NO_AGENTIC=""
RAW_MODE=""
STREAM_MODE=""
NO_FOLLOW=""
FORCE_FOLLOW=""
SHOW_TRACE="${{ORC_SHOW_TRACE:-}}"
QUERY_PARTS=()
while [ $# -gt 0 ]; do
    case "$1" in
        -s|--session)
            SESSION_ID="$2"
            shift 2
            ;;
        --new-session)
            NEW_SESSION="1"
            shift
            ;;
        --no-agentic)
            NO_AGENTIC="1"
            shift
            ;;
        --raw)
            RAW_MODE="1"
            shift
            ;;
        --no-follow)
            NO_FOLLOW="1"
            shift
            ;;
        --follow)
            FORCE_FOLLOW="1"
            shift
            ;;
        --show-trace|--trace|--debug)
            SHOW_TRACE="1"
            shift
            ;;
        --stream)
            # streaming is already the default; accept the flag as a no-op
            shift
            ;;
        --no-stream)
            NO_STREAM_MODE="1"
            shift
            ;;
        *)
            QUERY_PARTS+=("$1")
            shift
            ;;
    esac
done

QUERY="${{QUERY_PARTS[*]:-}}"
CLIENT_CWD=$(pwd -P 2>/dev/null || pwd)

# --- Resolve persistent default session (config-driven) ---
# Precedence: explicit -s/--session > cwd-scoped persisted default (unless --new-session) > none.
if [ -n "$CLI_DEFAULT_SESSION" ] && [ -n "$SESSION_STATE_FILE" ]; then
    STATE_BASE_PATH=$(eval echo "$SESSION_STATE_FILE")
    STATE_SCOPE=$(printf '%s' "$CLIENT_CWD" | python3 -c "import hashlib,sys; print(hashlib.sha1(sys.stdin.read().encode()).hexdigest()[:12])" 2>/dev/null || printf 'default')
    STATE_PATH="${{STATE_BASE_PATH}}.${{STATE_SCOPE}}"
    if [ -n "$NEW_SESSION" ]; then
        rm -f "$STATE_PATH" 2>/dev/null || true
    fi
    if [ -z "$SESSION_ID" ]; then
        if [ -s "$STATE_PATH" ]; then
            SESSION_ID=$(tr -d '\\n\\r' < "$STATE_PATH")
        fi
        if [ -z "$SESSION_ID" ]; then
            if command -v uuidgen &>/dev/null; then
                SESSION_ID=$(uuidgen)
            else
                SESSION_ID="cli-$(date +%s)-$$"
            fi
            mkdir -p "$(dirname "$STATE_PATH")" 2>/dev/null || true
            printf '%s' "$SESSION_ID" > "$STATE_PATH" 2>/dev/null || true
        fi
    fi
fi
# --- Read stdin if piped ---
STDIN_CONTENT=""
if [ -z "$QUERY" ] && [ ! -t 0 ]; then
    STDIN_CONTENT=$(cat)
fi

if [ -n "$STDIN_CONTENT" ]; then
    if [ -n "$QUERY" ]; then
        QUERY="$QUERY\\n\\n$STDIN_CONTENT"
    else
        QUERY="$STDIN_CONTENT"
    fi
fi

if [ -z "$QUERY" ]; then
    echo "Usage: {alias} your question" >&2
    echo "       cat file.py | {alias} analyse this" >&2
    echo "       {alias} --no-agentic simple question" >&2
    echo "       {alias} --raw plain text output" >&2
    echo "       {alias} --follow  show task timeline after the response" >&2
    echo "       {alias} --no-follow  keep the fast path without task timeline follow" >&2
    echo "       {alias} --show-trace  show task/trace metadata" >&2
    echo "       {alias} --no-stream  disable live streaming" >&2
    echo "       {alias} --new-session  reset conversation context" >&2
    echo "       {alias} -s ID continue this topic  use an explicit session id" >&2
    exit 1
fi

if [[ "$QUERY" == "/tasks" || "$QUERY" == "/tasks "* ]]; then
    read -r _tasks_cmd _tasks_id _tasks_rest <<< "$QUERY"
    if [ -n "${{_tasks_id:-}}" ] && [[ "$_tasks_id" != --* ]]; then
        exec symbiont --task "$_tasks_id" --watch
    fi
    exec symbiont -l
fi

# --- Build JSON payload ---
JSON_CLIENT_CWD=$(printf '%s' "$CLIENT_CWD" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))" 2>/dev/null \\
    || printf '%s' "$CLIENT_CWD" | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g' | sed 's/.*/"\\"&\\""/')
{client_system_probe}
{client_file_probe}

JSON_QUERY=$(printf '%s' "$QUERY" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))" 2>/dev/null \\
    || printf '%s' "$QUERY" | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g; s/\\t/\\\\t/g' | sed ':a;N;$!ba;s/\\n/\\\\n/g' | sed 's/.*/"\\"&\\""/')

# Streaming is on by default — shows pipeline status + live tokens.
# Pass --no-stream to use the synchronous (blocking) path instead.
STREAM_MODE="1"
STREAM_FLAG="true"
if [ -n "${{NO_STREAM_MODE:-}}" ]; then
    STREAM_MODE=""
    STREAM_FLAG="false"
fi

PAYLOAD="{{\\"query\\": $JSON_QUERY, \\"model\\": \\"{alias}\\", \\"stream\\": $STREAM_FLAG, \\"client_cwd\\": $JSON_CLIENT_CWD, \\"client_system\\": $CLIENT_SYSTEM_JSON, \\"client_files\\": $CLIENT_FILES_JSON"
if [ -n "$SESSION_ID" ]; then
    PAYLOAD="$PAYLOAD, \\"session_id\\": \\"$SESSION_ID\\""
fi
if [ -n "$NO_AGENTIC" ]; then
    PAYLOAD="$PAYLOAD, \\"agentic\\": false"
fi
PAYLOAD="$PAYLOAD}}"

# --- Determine render mode ---
# If output is piped or --raw, skip rendering; otherwise use the rich renderer
USE_RENDERER=""
if [ -t 1 ] && [ -z "$RAW_MODE" ] && [ -f "$ORC_RENDER" ] && command -v python3 &>/dev/null; then
    USE_RENDERER="1"
fi

ORC_FOLLOW_TASKS="${{ORC_FOLLOW_TASKS:-}}"
if [ -n "$NO_AGENTIC" ] || [ -n "$RAW_MODE" ] || [ ! -t 1 ]; then
    ORC_FOLLOW_TASKS=""
fi
if [ -n "$NO_FOLLOW" ]; then
    ORC_FOLLOW_TASKS=""
fi
if [ -n "$FORCE_FOLLOW" ]; then
    ORC_FOLLOW_TASKS="1"
fi

# --- Request response with optional live streaming + accumulate for final render ---
TMPFILE=$(mktemp /tmp/orc-stream.XXXXXX)
TRACEFILE=$(mktemp /tmp/orc-task.XXXXXX)
FOLLOW_LAST_FILE=$(mktemp /tmp/orc-follow-last.XXXXXX)
HEADERFILE=$(mktemp /tmp/orc-headers.XXXXXX)
PAYLOADFILE=$(mktemp /tmp/orc-payload.XXXXXX)
trap 'rm -f "$TMPFILE" "$TRACEFILE" "$FOLLOW_LAST_FILE" "$HEADERFILE" "$PAYLOADFILE"' EXIT
printf 'X-API-Key: %s\n' "$ORC_SYMBIONT_API_KEY" > "$HEADERFILE"
printf '%s' "$PAYLOAD" > "$PAYLOADFILE"

_orc_capture_task_meta() {{
    if ! command -v python3 &>/dev/null; then
        return 0
    fi
    meta=$(printf '%s' "$1" | python3 -c 'import json, sys
try:
    data = json.loads(sys.stdin.read())
except Exception:
    raise SystemExit(0)
task_id = data.get("task_id") or data.get("id") or ""
trace_id = data.get("trace_id") or ""
session_id = data.get("session_id") or ""
if task_id:
    print(str(task_id) + "\\t" + str(trace_id) + "\\t" + str(session_id))
' 2>/dev/null || true)
    if [ -n "$meta" ]; then
        printf '%s\n' "$meta" > "$TRACEFILE"
    fi
}}

_orc_task_id() {{
    if [ -s "$TRACEFILE" ]; then
        awk 'NR == 1 {{print $1}}' "$TRACEFILE"
    fi
}}

_orc_session_id() {{
    if [ -s "$TRACEFILE" ]; then
        awk 'NR == 1 {{print $3}}' "$TRACEFILE"
    fi
}}

_orc_render_timeline_snapshot() {{
    reason="${{1:-update}}"
    [ -n "$ORC_FOLLOW_TASKS" ] || return 0
    task_id=$(_orc_task_id)
    [ -n "$task_id" ] || return 0
    now=$(date +%s)
    last=0
    if [ -s "$FOLLOW_LAST_FILE" ]; then
        last=$(cat "$FOLLOW_LAST_FILE" 2>/dev/null || printf '0')
    fi
    if [ "$reason" != "final" ] && [ $((now - last)) -lt 4 ]; then
        return 0
    fi
    printf '%s' "$now" > "$FOLLOW_LAST_FILE"
    printf '\n\033[2mTask UI (%s): symbiont --task %s --watch\033[0m\n' "$reason" "$task_id" >/dev/tty
}}

if [ -n "$STREAM_MODE" ]; then
    set +e
    HTTP_CODE=$(curl -skS -w "\\n__HTTPCODE__:%{{http_code}}" \\
        -X POST "$ORC_API_URL/query" \\
        -H "Content-Type: application/json" \\
        -H "@$HEADERFILE" \\
        --data-binary "@$PAYLOADFILE" \\
        --no-buffer 2>/dev/null | {{
        LAST_EVENT=""
        STATUS_SHOWN=""
        while IFS= read -r line || [[ -n "$line" ]]; do
            line="${{line%$'\\r'}}"
            if [[ "$line" == event:* ]]; then
                LAST_EVENT="${{line#event: }}"
            elif [[ "$line" == data:* ]]; then
                chunk="${{line#data: }}"
                if [ "$chunk" = "[DONE]" ]; then
                    LAST_EVENT=""
                elif [ "$LAST_EVENT" = "status_start" ]; then
                    # Live status while a step is running. Hide with ORC_HIDE_STATUS_START=1.
                    if [ -n "$USE_RENDERER" ] && [ -z "${{ORC_HIDE_STATUS_START:-}}" ]; then
                        printf '\\r\\033[K\\033[2m%s\\033[0m' "$chunk" >/dev/tty
                        STATUS_SHOWN="1"
                    fi
                elif [ "$LAST_EVENT" = "status_done" ] || [ "$LAST_EVENT" = "status" ]; then
                    # Completed pipeline step: print one clean diagnostic line and never add it to the response.
                    if [ -n "$USE_RENDERER" ]; then
                        if [ -n "$STATUS_SHOWN" ]; then
                            printf '\\r\\033[K' >/dev/tty
                            STATUS_SHOWN=""
                        fi
                        printf '\\033[2m%s\\033[0m\\n' "$chunk" >/dev/tty
                    fi
                    _orc_render_timeline_snapshot "update"
                elif [ "$LAST_EVENT" = "agentic" ]; then
                    # Agentic task/trace metadata is operational evidence, not assistant text.
                    _orc_capture_task_meta "$chunk"
                    if [ -n "$SHOW_TRACE" ]; then
                        printf '\\033[2m%s\\033[0m\\n' "$chunk" >/dev/tty 2>/dev/null || printf '%s\\n' "$chunk" >&2
                    fi
                    _orc_render_timeline_snapshot "started"
                elif [[ "$chunk" == '{{"task_id"'*'"trace_id"'* ]]; then
                    # Defensive filter for older gateways that emitted trace metadata without an event name.
                    _orc_capture_task_meta "$chunk"
                    if [ -n "$SHOW_TRACE" ]; then
                        printf '\\033[2m%s\\033[0m\\n' "$chunk" >/dev/tty 2>/dev/null || printf '%s\\n' "$chunk" >&2
                    fi
                    _orc_render_timeline_snapshot "started"
                else
                    # Regular response token — accumulate for final render only
                    # (raw tokens are NOT written to tty; the re-rendered output is cleaner)
                    if [ -n "$STATUS_SHOWN" ]; then
                        STATUS_SHOWN=""
                    fi
                    # Handle escaped newline tokens from SSE
                    if [ "$chunk" = '\\n' ]; then
                        chunk=$'\\n'
                    fi
                    # Accumulate full text for final render
                    printf '%s' "$chunk" >> "$TMPFILE"
                fi
            elif [[ -z "$line" ]]; then
                LAST_EVENT=""
            elif [[ "$line" == __HTTPCODE__:* ]]; then
                printf '%s' "${{line#__HTTPCODE__:}}"
            fi
        done
        }})
    set -e
else
    set +e
    RESPONSE=$(curl -skS -w "\\n__HTTPCODE__:%{{http_code}}" \\
        -X POST "$ORC_API_URL/query" \\
        -H "Content-Type: application/json" \\
        -H "@$HEADERFILE" \\
        --data-binary "@$PAYLOADFILE" 2>/dev/null)
    CURL_EXIT=$?
    set -e

    if [ "$CURL_EXIT" -ne 0 ]; then
        HTTP_CODE="000"
    else
        HTTP_CODE="${{RESPONSE##*__HTTPCODE__:}}"
        BODY="${{RESPONSE%$'\\n'__HTTPCODE__:*}}"
        if command -v python3 &>/dev/null; then
            printf '%s' "$BODY" | python3 -c "import sys,json; data=json.load(sys.stdin); print(data.get('response',''))" > "$TMPFILE" 2>/dev/null \\
                || printf '%s' "$BODY" > "$TMPFILE"
        else
            printf '%s' "$BODY" > "$TMPFILE"
        fi
    fi
fi

# Handle HTTP errors
case "${{HTTP_CODE:-000}}" in
    200) ;;
    000) echo "" >&2; echo "Error: Symbiont not running. Start with: make infra" >&2; rm -f "$TMPFILE"; exit 1 ;;
    401) echo "" >&2; echo "Error: Invalid API key." >&2; rm -f "$TMPFILE"; exit 1 ;;
    422) echo "" >&2; echo "Error: Invalid query." >&2; rm -f "$TMPFILE"; exit 1 ;;
    429) echo "" >&2; echo "Error: LLM busy — try again shortly." >&2; rm -f "$TMPFILE"; exit 1 ;;
    *)   echo "" >&2; echo "Error: API returned HTTP $HTTP_CODE" >&2; rm -f "$TMPFILE"; exit 1 ;;
esac

# --- Final render: replace raw stream with beautifully formatted output ---
if [ -n "$USE_RENDERER" ] && [ -s "$TMPFILE" ]; then
    CONTENT=$(cat "$TMPFILE")

    # Check for notification marker and fire notify-send
    if echo "$CONTENT" | grep -q "__NOTIFY__:"; then
        NOTIFY_LINE=$(echo "$CONTENT" | grep "__NOTIFY__:" | head -1)
        NOTIFY_TITLE=$(echo "$NOTIFY_LINE" | cut -d: -f2)
        NOTIFY_MSG=$(echo "$NOTIFY_LINE" | cut -d: -f3-)
        if command -v notify-send &>/dev/null; then
            notify-send --app-name="AI Symbiont" "$NOTIFY_TITLE" "$NOTIFY_MSG" 2>/dev/null &
        fi
        # Remove the marker line from content
        CONTENT=$(echo "$CONTENT" | grep -v "__NOTIFY__:" || true)
    fi

    # Clear the status label line and re-render with Markdown.
    if [ -n "$STREAM_MODE" ]; then
        printf '\\r\\033[K' > /dev/tty
    fi

    # Re-render with full Markdown formatting
    printf '%s' "$CONTENT" | python3 "$ORC_RENDER"
elif [ -s "$TMPFILE" ]; then
    # No renderer available or piped output — output plain text
    CONTENT=$(cat "$TMPFILE")

    # Check for notification marker and fire notify-send
    if echo "$CONTENT" | grep -q "__NOTIFY__:"; then
        NOTIFY_LINE=$(echo "$CONTENT" | grep "__NOTIFY__:" | head -1)
        NOTIFY_TITLE=$(echo "$NOTIFY_LINE" | cut -d: -f2)
        NOTIFY_MSG=$(echo "$NOTIFY_LINE" | cut -d: -f3-)
        if command -v notify-send &>/dev/null; then
            notify-send --app-name="AI Symbiont" "$NOTIFY_TITLE" "$NOTIFY_MSG" 2>/dev/null &
        fi
        # Remove the marker line from content
        CONTENT=$(echo "$CONTENT" | grep -v "__NOTIFY__:" || true)
    fi

    if [ ! -t 1 ]; then
        printf '%s' "$CONTENT"
    fi
    echo ""
else
    echo ""
fi

if [ -n "$ORC_FOLLOW_TASKS" ]; then
    task_id=$(_orc_task_id)
    if [ -n "$task_id" ]; then
        session_id=$(_orc_session_id)
        rm -f "$TMPFILE" "$TRACEFILE" "$FOLLOW_LAST_FILE"
        if [ -n "$session_id" ]; then
            exec symbiont --session "$session_id" --task "$task_id" --watch
        fi
        exec symbiont --task "$task_id" --watch
    fi
fi

rm -f "$TMPFILE"
'''


def _build_symbiont_launcher(*, services_env_file: str = "", secret_file: str = "") -> str:
    """Build the primary interactive ``symbiont`` launcher."""
    services_env_file = services_env_file or _ENV_FILE_PATH
    secret_file = secret_file or _SECRET_FILE
    return f'''#!/usr/bin/env bash
{_ALIAS_MARKER}
# Primary interactive Symbiont terminal UX.
set -euo pipefail

SERVICES_ENV_FILE="{services_env_file}"
ORC_API_URL="${{ORC_API_URL:-}}"
if [ -z "$ORC_API_URL" ] && [ -f "$SERVICES_ENV_FILE" ]; then
    ORC_PORT=$(sed -n 's/^ORC_PORT_SYMBIONT=//p' "$SERVICES_ENV_FILE" | tail -n 1 | tr -d '\\n\\r')
    if [ -n "$ORC_PORT" ]; then
        ORC_API_URL="https://127.0.0.1:$ORC_PORT"
    fi
fi
ORC_API_URL="${{ORC_API_URL:-https://127.0.0.1:8586}}"
SECRET_FILE="{secret_file}"
ORC_SYMBIONT_TUI="{_symbiont_tui_binary_path()}"
CLIENT_CWD=$(pwd -P 2>/dev/null || pwd)

if [ ! -x "$ORC_SYMBIONT_TUI" ]; then
    echo "Error: Symbiont Rust terminal not installed." >&2
    echo "Build it with: cargo build --release --manifest-path {_symbiont_tui_crate_dir() / 'Cargo.toml'}" >&2
    echo "Then run: make aliases" >&2
    exit 1
fi

case "${{1:-}}" in
    -l|--live|--list)
        shift
        exec "$ORC_SYMBIONT_TUI" live --api-url "$ORC_API_URL" --api-key-file "$SECRET_FILE" --cwd "$CLIENT_CWD" "$@"
        ;;
    *)
        exec "$ORC_SYMBIONT_TUI" chat --api-url "$ORC_API_URL" --api-key-file "$SECRET_FILE" --cwd "$CLIENT_CWD" "$@"
        ;;
esac
'''


def get_script_template() -> str:
    """Return the script template for testing purposes."""
    return _build_script(
        "__test__",
        "/dev/null",
        cli_default_session=True,
        session_state_file=_DEFAULT_CLI_SESSION_STATE_FILE,
    )


def _install_render_script(bin_dir: Path) -> None:
    """Install the private streaming Markdown→ANSI helper."""
    render_src = Path(__file__).resolve().parent / "render.py"
    render_dst = _user_lib_dir() / "orc-render"

    if render_src.exists():
        _atomic_copy_executable(render_src, render_dst)


def _atomic_copy_executable(src: Path, dst: Path) -> None:
    """Install an executable without rewriting a running binary in place."""
    import shutil

    dst.parent.mkdir(parents=True, exist_ok=True)
    tmp = dst.with_name(f".{dst.name}.tmp-{os.getpid()}")
    try:
        shutil.copy2(src, tmp)
        tmp.chmod(tmp.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        tmp.replace(dst)
    finally:
        if tmp.exists():
            tmp.unlink()


def _install_symbiont_tui_binary(bin_dir: Path) -> bool:
    """Install the compiled Rust Symbiont terminal binary when available."""
    crate_dir = _symbiont_tui_crate_dir()
    installed = False
    for candidate in (
        crate_dir / "target" / "release" / "symbiont-tui",
        crate_dir / "target" / "debug" / "symbiont-tui",
    ):
        if candidate.exists():
            tui_dst = _user_lib_dir() / "symbiont-tui"
            _atomic_copy_executable(candidate, tui_dst)
            installed = True
            break

    for old_binary in (bin_dir / "symbiont-tui",):
        if old_binary.exists():
            old_binary.unlink()
    return installed


def install_aliases() -> dict[str, Path]:
    """Install the generated public terminal commands into ~/.local/bin/.

    The ``@`` compatibility alias is pure bash/curl. The primary ``symbiont``
    terminal launcher uses the private installed Rust TUI binary.
    Requires the symbiont API to be running (``make infra``).

    Returns dict of alias → script path for successfully installed aliases.
    """
    # Public CLI policy: keep exactly @ and symbiont as user-facing commands.
    # Registry aliases remain model metadata; they no longer become PATH commands.
    alias = "@"

    # Session continuity settings are sourced from [session] without loading
    # the full runtime config, so alias installation does not depend on LLM secrets.
    cli_default_session, session_state_file = _load_cli_session_settings()

    aliases = [alias]
    desired_aliases = set(aliases)

    bin_dir = _user_bin_dir()
    _install_render_script(bin_dir)
    tui_installed = _install_symbiont_tui_binary(bin_dir)
    if not tui_installed:
        click.echo(
            click.style(
                "  ⚠ symbiont-tui binary not found — run `make build-symbiont-tui` before using `symbiont`",
                fg="yellow",
            ),
            err=True,
        )
    installed: dict[str, Path] = {}

    for path in sorted(bin_dir.iterdir()):
        if not path.is_file() or path.name in desired_aliases:
            continue
        try:
            content = path.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        if _is_generated_alias_script(content):
            path.unlink()

    for alias in sorted(aliases):
        # Never shadow reserved system commands (e.g. VS Code's `code`)
        if alias in _RESERVED_NAMES:
            click.echo(
                click.style(f"  ⚠ Skipping '{alias}' — reserved system command name", fg="yellow"),
                err=True,
            )
            continue

        script_path = bin_dir / alias

        # Don't overwrite non-alias files (safety check)
        if script_path.exists():
            try:
                content = script_path.read_text()
                if not _is_generated_alias_script(content):
                    click.echo(
                        click.style(f"  ⚠ Skipping '{alias}' — file exists and is not an alias script", fg="yellow"),
                        err=True,
                    )
                    continue
            except (OSError, UnicodeDecodeError):
                continue

        script_content = _build_script(
            alias,
            _SECRET_FILE,
            cli_default_session=cli_default_session,
            session_state_file=session_state_file,
        )
        script_path.write_text(script_content)
        script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        installed[alias] = script_path

    symbiont_path = bin_dir / "symbiont"
    if symbiont_path.exists():
        try:
            content = symbiont_path.read_text()
            can_overwrite = _is_generated_alias_script(content)
        except (OSError, UnicodeDecodeError):
            can_overwrite = False
    else:
        can_overwrite = True
    if can_overwrite:
        symbiont_path.write_text(_build_symbiont_launcher())
        symbiont_path.chmod(symbiont_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        installed["symbiont"] = symbiont_path
    else:
        click.echo(
            click.style("  ⚠ Skipping 'symbiont' — file exists and is not an ai-local generated script", fg="yellow"),
            err=True,
        )

    for alias in installed:
        _install_zsh_noglob_alias(alias)

    return installed


def remove_aliases() -> list[str]:
    """Remove all auto-generated alias scripts from ~/.local/bin/.

    Returns list of removed alias names.
    """
    bin_dir = _user_bin_dir()
    removed: list[str] = []

    for path in sorted(bin_dir.iterdir()):
        if not path.is_file():
            continue
        try:
            content = path.read_text()
            if _is_generated_alias_script(content):
                path.unlink()
                removed.append(path.name)
        except (OSError, UnicodeDecodeError):
            continue

    return removed
