"""Generated host-level Ollama configuration."""

from __future__ import annotations

import math
import os
from typing import Any


def _env_override(key: str, default: str) -> str:
    value = os.environ.get(key)
    if value is None or value.strip() == "":
        return default
    return value.strip()


def _systemd_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _memory_gb(runtime: dict[str, Any], fraction: float, minimum: int) -> str | None:
    total = runtime.get("ram_total_gb")
    if total is None:
        return None
    try:
        value = max(minimum, math.floor(float(total) * fraction))
    except (TypeError, ValueError):
        return None
    return f"{value}G"


def resolve_ollama_host_config(resolved: dict[str, Any]) -> dict[str, Any]:
    """Return host systemd settings for a native Ollama service."""

    config = resolved["config"]
    runtime = resolved["runtime"]
    profile = str(config.get("hardware", {}).get("profile", "auto"))
    gpu_enabled = profile != "cpu_only" and bool(runtime.get("gpu_available"))

    env = {
        "OLLAMA_KEEP_ALIVE": _env_override("AI_OLLAMA_KEEP_ALIVE", "2h"),
        "OLLAMA_MAX_LOADED_MODELS": _env_override("AI_OLLAMA_MAX_LOADED_MODELS", "1"),
        "OLLAMA_NUM_PARALLEL": _env_override("AI_OLLAMA_NUM_PARALLEL", "1"),
    }
    if gpu_enabled:
        env.update(
            {
                "CUDA_VISIBLE_DEVICES": _env_override("AI_OLLAMA_CUDA_VISIBLE_DEVICES", "0"),
                "OLLAMA_FLASH_ATTENTION": _env_override("AI_OLLAMA_FLASH_ATTENTION", "1"),
                "OLLAMA_KV_CACHE_TYPE": _env_override("AI_OLLAMA_KV_CACHE_TYPE", "q8_0"),
                "OLLAMA_NUM_GPU": _env_override("AI_OLLAMA_NUM_GPU", "-1"),
            }
        )
    elif profile == "cpu_only":
        env["OLLAMA_NUM_GPU"] = _env_override("AI_OLLAMA_NUM_GPU", "0")

    service = {
        "LimitNOFILE": _env_override("AI_OLLAMA_LIMIT_NOFILE", "65536"),
        "OOMScoreAdjust": _env_override("AI_OLLAMA_OOM_SCORE_ADJUST", "-500"),
    }
    memory_high = _memory_gb(runtime, 0.75, 4)
    memory_max = _memory_gb(runtime, 0.875, 6)
    if memory_high:
        service["MemoryHigh"] = _env_override("AI_OLLAMA_MEMORY_HIGH", memory_high)
    if memory_max:
        service["MemoryMax"] = _env_override("AI_OLLAMA_MEMORY_MAX", memory_max)

    return {
        "service": "ollama.service",
        "dropin_name": "90-ai-local.conf",
        "gpu_enabled": gpu_enabled,
        "env": env,
        "service_settings": service,
        "override_env": "AI_OLLAMA_*",
    }


def format_ollama_systemd_override(ollama_host: dict[str, Any]) -> str:
    """Format the generated Ollama systemd drop-in."""

    lines = [
        "# Auto-generated by python -m config.resolver --write-ollama-host-config",
        "# Do not edit this file in /etc directly; rerun make ollama-host-config.",
        "",
        "[Service]",
    ]
    for key, value in ollama_host["env"].items():
        lines.append(f'Environment="{key}={_systemd_quote(str(value))}"')
    if ollama_host["service_settings"]:
        lines.append("")
    for key, value in ollama_host["service_settings"].items():
        lines.append(f"{key}={value}")
    lines.append("")
    return "\n".join(lines)


def format_ollama_apply_script() -> str:
    """Return an idempotent script that installs the generated drop-in."""

    return """#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DROPIN_SOURCE="${SOURCE_DIR}/90-ai-local.conf"
DROPIN_DIR="${OLLAMA_SYSTEMD_DROPIN_DIR:-/etc/systemd/system/ollama.service.d}"
DROPIN_TARGET="${DROPIN_DIR}/90-ai-local.conf"

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "Ollama host config apply is only supported on Linux/systemd hosts." >&2
  exit 1
fi

if ! command -v systemctl >/dev/null 2>&1; then
  echo "systemctl was not found; cannot apply Ollama systemd configuration." >&2
  exit 1
fi

if [[ ! -f "${DROPIN_SOURCE}" ]]; then
  echo "Missing generated drop-in: ${DROPIN_SOURCE}" >&2
  exit 1
fi

sudo mkdir -p "${DROPIN_DIR}"
sudo install -m 0644 "${DROPIN_SOURCE}" "${DROPIN_TARGET}"
sudo systemctl daemon-reload
sudo systemctl restart ollama

echo "Applied ${DROPIN_TARGET}"
systemctl show ollama --property=Environment --no-pager
"""
