INSERT INTO llm_call_log (
    request_id, session_id, timestamp, date, hour, weekday, entrypoint,
    model, backend, intent, complexity,
    requested_model, fallback_used, fallback_reason, blocked_backends,
    privacy_mode, decision_reason,
    prompt_tokens, completion_tokens, total_tokens, usage_source,
    stream, chunks_count,
    latency_ms, first_token_latency_ms, context_latency_ms, llm_latency_ms,
    router_latency_ms, context_build_latency_ms, model_load_latency_ms,
    prompt_eval_latency_ms, generation_latency_ms, total_latency_ms,
    cold_start, prompt_tokens_per_second, generation_tokens_per_second, total_tokens_per_second,
    ollama_total_duration, ollama_load_duration,
    ollama_prompt_eval_count, ollama_prompt_eval_duration,
    ollama_eval_count, ollama_eval_duration,
    profile_key,
    query_length, response_length, query_hash,
    prompt_preview, response_preview,
    rag_used, graph_used, tools_used, agentic, iterations,
    success, error_type, error_message
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?,
    ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?
)
